# Generated by Django 4.1.3 on 2022-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='born_date',
            field=models.DateField(auto_now=True, verbose_name='Дата рождения'),
        ),
    ]
