# Generated by Django 4.1.3 on 2022-12-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stadium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ('-perimetr',), 'verbose_name': 'стадион', 'verbose_name_plural': 'стадионы'},
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.stadium', verbose_name='stadium'),
        ),
    ]
